version: '2'
services:
  my-loadbalancer:
    image: rancher/lb-service-haproxy:v0.7.9
    ports:
    - 1117:1117/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
      io.rancher.scheduler.global: 'true'
  blog:
    image: ghost
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
